# Generated by Django 6.0.3 on 2026-03-21 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=100)),
                ('date', models.CharField(max_length=100)),
                ('time', models.CharField(max_length=20)),
                ('location', models.CharField(max_length=200)),
                ('price', models.PositiveIntegerField()),
                ('image', models.URLField(max_length=500)),
                ('description', models.TextField()),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
